### GET all usuarios
GET http://localhost:3000/users
Accept: application/json

### GET un usuario
GET http://localhost:3000/users/1
Accept: application/json

### POST un usuario
POST http://localhost:3000/users
Content-Type: application/json

{
    "id": 3,
    "name": "James",
    "email": "James@mail.com" 
}

### PUT en un usuario
PUT http://localhost:3000/users/3
Content-Type: application/json

{
    "id": 1,
    "name": "James",
    "email": "James@mail.com" 
}

### DELETE un usuario
DELETE http://localhost:3000/users/1